### PR TITLE
[minor] Now filtering <username>.nodejitsu.com out

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by jfhbrook** [comment]
I see what this pull request does, but I'm not sure what the rationale is. Why do you want to filter out <username>.nodejitsu.com ?

**Comment by pksunkara** [comment]
what happened was that I changed the app name from nodeapps-my-nodeapps to something else before deploying but I deployed it to my username.nodejitsu.com, so I kinda just forked it and sent a request while I was sleepy.

Now that I think of it, it's probably not a good idea because we are assuming that they upload nodeapps-my-nodeapps to username.nodejitsu.com

**Comment by jfhbrook** [comment]
I see.

Maybe the way to do this is to use pkginfo to get the name of the app. That way, people can rename it.

I'll go ahead and close this pull request, but I'll open a ticket for pkginfo action. That'd be sweet.

**Comment by pksunkara** [comment]
I concur

**Pull request closed without merging**
